# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Hugues/AppData/Local/Temp/mainnsHcFS.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 539)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setGeometry(QtCore.QRect(10, 10, 660, 521))
        self.dropShadowFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(56,58,89);\n"
"    color : rgb(220,220,220);\n"
"    border-radius:10px;\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.label_title = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_title.setGeometry(QtCore.QRect(0, 10, 661, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("QLabel{\n"
"color:#22e5c5;\n"
"}\n"
"QLabel::hover{\n"
"    color:#00fd98;;\n"
"}")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.btnSelect = QtWidgets.QPushButton(self.dropShadowFrame)
        self.btnSelect.setGeometry(QtCore.QRect(60, 460, 101, 41))
        self.btnSelect.setStyleSheet("QPushButton{\n"
"    background-color: rgb(34, 229, 197);\n"
"    color:rgb(50,50,50);\n"
"    border-radius:10px;\n"
"    font-size:13px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#00fd98;\n"
"    color:rgb(50,50,50);\n"
"}")
        self.btnSelect.setObjectName("btnSelect")
        self.btnExtract = QtWidgets.QPushButton(self.dropShadowFrame)
        self.btnExtract.setGeometry(QtCore.QRect(280, 460, 91, 41))
        self.btnExtract.setStyleSheet("QPushButton{\n"
"    background-color: rgb(34, 229, 197);\n"
"    color:rgb(50,50,50);\n"
"    border-radius:10px;\n"
"    font-size:13px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:#00fd98;\n"
"    color:rgb(50,50,50);\n"
"}")
        self.btnExtract.setObjectName("btnExtract")
        self.btnFile = QtWidgets.QPushButton(self.dropShadowFrame)
        self.btnFile.setGeometry(QtCore.QRect(510, 460, 101, 41))
        self.btnFile.setStyleSheet("QPushButton{\n"
"    background-color: rgb(34, 229, 197);\n"
"    color:rgb(50,50,50);\n"
"    border-radius:10px;\n"
"    font-size:13px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#00fd98;\n"
"    color:rgb(50,50,50);\n"
"}")
        self.btnFile.setObjectName("btnFile")
        self.imgSelect = QtWidgets.QLabel(self.dropShadowFrame)
        self.imgSelect.setGeometry(QtCore.QRect(10, 100, 311, 341))
        self.imgSelect.setStyleSheet("QLabel{\n"
"    border:1px solid;\n"
"}")
        self.imgSelect.setText("")
        self.imgSelect.setObjectName("imgSelect")
        self.labelExtract = QtWidgets.QLabel(self.dropShadowFrame)
        self.labelExtract.setGeometry(QtCore.QRect(340, 100, 311, 341))
        self.labelExtract.setStyleSheet("QLabel{\n"
"    border:1px solid;\n"
"}")
        self.labelExtract.setText("")
        self.labelExtract.setObjectName("labelExtract")
        self.btnExit = QtWidgets.QPushButton(self.dropShadowFrame)
        self.btnExit.setGeometry(QtCore.QRect(610, 10, 41, 21))
        self.btnExit.setStyleSheet("QPushButton{\n"
"    background-color: rgb(34, 229, 197);\n"
"    color:rgb(50,50,50);\n"
"    border-radius:10px;\n"
"    font-size:13px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#00fd98;\n"
"    color:rgb(50,50,50);\n"
"}\n"
"")
        self.btnExit.setText("")
        self.btnExit.setObjectName("btnExit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text Extract"))
        self.label_title.setText(_translate("MainWindow", "<strong>Text</strong> Extract"))
        self.btnSelect.setText(_translate("MainWindow", "Select Image"))
        self.btnExtract.setText(_translate("MainWindow", "Extract Text"))
        self.btnFile.setText(_translate("MainWindow", " PDF File"))
